USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_LAKEHOUSE;
USE SCHEMA MART;

CREATE OR REPLACE SECURE VIEW VW_CUSTOMER_ANALYTICS AS

SELECT

    CUSTOMER_KEY,
    CUSTOMER_CITY,
    CUSTOMER_STATE

FROM DIM_CUSTOMERS;