CREATE OR REPLACE ROW ACCESS POLICY STATE_POLICY

AS (CUSTOMER_STATE STRING)

RETURNS BOOLEAN ->

CASE

    WHEN CURRENT_ROLE() = 'DATA_ENGINEER_ROLE'
    THEN TRUE

    WHEN CURRENT_ROLE() = 'BI_ANALYST_ROLE'
    THEN CUSTOMER_STATE = 'SP'

    ELSE FALSE

END;

ALTER TABLE MART.DIM_CUSTOMERS

ADD ROW ACCESS POLICY STATE_POLICY

ON (CUSTOMER_STATE);