SHOW MASKING POLICIES;

SHOW ROW ACCESS POLICIES;

-- Test Role
GRANT ROLE BI_ANALYST_ROLE TO USER xxx;
USE ROLE BI_ANALYST_ROLE;

SELECT *
FROM MART.DIM_CUSTOMERS;

GRANT ROLE DATA_ENGINEER_ROLE TO USER xxx;

USE ROLE DATA_ENGINEER_ROLE;

SELECT *
FROM MART.DIM_CUSTOMERS;