USE DATABASE RETAIL_LAKEHOUSE;
USE SCHEMA MART;

CREATE OR REPLACE TABLE DIM_CUSTOMERS AS
SELECT
    ROW_NUMBER() OVER(
        ORDER BY CUSTOMER_ID
    ) AS CUSTOMER_KEY,

    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_CITY,
    CUSTOMER_STATE

FROM TRANSFORM.CUSTOMERS_CLEAN;