USE DATABASE RETAIL_LAKEHOUSE;
USE SCHEMA MART;

CREATE OR REPLACE TABLE MART.DIM_PRODUCTS AS
SELECT
    ROW_NUMBER() OVER(
        ORDER BY PRODUCT_ID
    ) AS PRODUCT_KEY,

    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_WEIGHT_G

FROM TRANSFORM.PRODUCTS_CLEAN;