USE DATABASE RETAIL_LAKEHOUSE;
USE SCHEMA MART;

CREATE OR REPLACE TABLE MART.DIM_DATE AS
SELECT
    ROW_NUMBER() OVER(
        ORDER BY DATE_DAY
    ) AS DATE_KEY,

    DATE_DAY,

    YEAR(DATE_DAY) AS YEAR,

    MONTH(DATE_DAY) AS MONTH,

    DAY(DATE_DAY) AS DAY,

    QUARTER(DATE_DAY) AS QUARTER

FROM (
    SELECT
        DATEADD(
            DAY,
            SEQ4(),
            '2016-01-01'
        ) AS DATE_DAY
    FROM TABLE(
        GENERATOR(ROWCOUNT => 5000)
    )
);
