USE DATABASE RETAIL_LAKEHOUSE;
USE SCHEMA MART;
CREATE OR REPLACE TABLE MART.DIM_PAYMENTS AS
SELECT DISTINCT

    ROW_NUMBER() OVER(
        ORDER BY PAYMENT_TYPE
    ) AS PAYMENT_KEY,

    PAYMENT_TYPE

FROM TRANSFORM.PAYMENTS_CLEAN;