CREATE OR REPLACE TABLE MART.FACT_ORDERS AS

SELECT

    dc.CUSTOMER_KEY,

    dp.PRODUCT_KEY,

    dd.DATE_KEY,

    dpay.PAYMENT_KEY,

    oi.ORDER_ID,

    oi.PRICE,

    oi.FREIGHT_VALUE,

    p.PAYMENT_VALUE

FROM TRANSFORM.ORDER_ITEMS_CLEAN oi

JOIN TRANSFORM.ORDERS_CLEAN o
ON oi.ORDER_ID = o.ORDER_ID

JOIN MART.DIM_CUSTOMERS dc
ON o.CUSTOMER_ID = dc.CUSTOMER_ID

JOIN MART.DIM_PRODUCTS dp
ON oi.PRODUCT_ID = dp.PRODUCT_ID

JOIN TRANSFORM.PAYMENTS_CLEAN p
ON oi.ORDER_ID = p.ORDER_ID

JOIN MART.DIM_PAYMENTS dpay
ON p.PAYMENT_TYPE = dpay.PAYMENT_TYPE

JOIN MART.DIM_DATE dd
ON CAST(o.ORDER_PURCHASE_TIMESTAMP AS DATE)
    = dd.DATE_DAY;