-- Total Revenue
SELECT
    SUM(PAYMENT_VALUE)
FROM MART.FACT_ORDERS;

-- Monthly Revenue
SELECT
    d.YEAR,
    d.MONTH,
    SUM(f.PAYMENT_VALUE) AS REVENUE
FROM MART.FACT_ORDERS f
JOIN MART.DIM_DATE d
ON f.DATE_KEY = d.DATE_KEY
GROUP BY 1,2
ORDER BY 1,2;

-- Top Products
SELECT
    p.PRODUCT_CATEGORY_NAME,
    SUM(f.PAYMENT_VALUE)
FROM MART.FACT_ORDERS f
JOIN MART.DIM_PRODUCTS p
ON f.PRODUCT_KEY = p.PRODUCT_KEY
GROUP BY 1
ORDER BY 2 DESC;