SHOW TABLES IN SCHEMA MART;

SELECT *
FROM MART.DIM_CUSTOMERS
AT (OFFSET => -60 * 5);

-- Accidental Delete
DELETE FROM MART.DIM_CUSTOMERS;

-- Time Travel to recover data
CREATE OR REPLACE TABLE MART.DIM_CUSTOMERS_RECOVERED AS

SELECT *
FROM MART.DIM_CUSTOMERS
AT (OFFSET => -60 * 5);