-- Storage Integration
-- Azure Blob Storage Integration

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION AZURE_RETAIL_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = AZURE
ENABLED = TRUE
AZURE_TENANT_ID = '86b9dd87-6406-4c24-9983-04456c775f1b'
STORAGE_ALLOWED_LOCATIONS =
(
'azure://retaillakehouse523.blob.core.windows.net/retail-data/'
);

DESC INTEGRATION AZURE_RETAIL_INT;