USE ROLE ACCOUNTADMIN;

USE DATABASE RETAIL_LAKEHOUSE;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE AZURE_RETAIL_STAGE
URL='azure://retaillakehouse523.blob.core.windows.net/retail-data'
STORAGE_INTEGRATION = AZURE_RETAIL_INT
FILE_FORMAT = CSV_FORMAT;

LIST @AZURE_RETAIL_STAGE;