USE DATABASE RETAIL_LAKEHOUSE;
USE SCHEMA RAW;

CREATE OR REPLACE PIPE CUSTOMERS_PIPE
AUTO_INGEST = FALSE
AS
COPY INTO RAW_CUSTOMERS
FROM @AZURE_RETAIL_STAGE/customers/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

CREATE OR REPLACE PIPE ORDERS_PIPE
AUTO_INGEST = FALSE
AS
COPY INTO RAW_ORDERS
FROM @AZURE_RETAIL_STAGE/orders/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

CREATE OR REPLACE PIPE PRODUCTS_PIPE
AUTO_INGEST = FALSE
AS
COPY INTO RAW_PRODUCTS
FROM @AZURE_RETAIL_STAGE/products/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

CREATE OR REPLACE PIPE ORDER_ITEMS_PIPE
AUTO_INGEST = FALSE
AS
COPY INTO RAW_ORDER_ITEMS
FROM @AZURE_RETAIL_STAGE/order_items/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

CREATE OR REPLACE PIPE PAYMENTS_PIPE
AUTO_INGEST = FALSE
AS
COPY INTO RAW_PAYMENTS
FROM @AZURE_RETAIL_STAGE/payments/
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);