USE DATABASE RETAIL_LAKEHOUSE;
USE SCHEMA RAW;

SHOW PIPES;

SELECT SYSTEM$PIPE_STATUS('CUSTOMERS_PIPE');
SELECT SYSTEM$PIPE_STATUS('ORDERS_PIPE');
SELECT SYSTEM$PIPE_STATUS('PRODUCTS_PIPE');
SELECT SYSTEM$PIPE_STATUS('ORDER_ITEMS_PIPE');
SELECT SYSTEM$PIPE_STATUS('PAYMENTS_PIPE');

SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME=>'RAW_CUSTOMERS',
        START_TIME=>DATEADD('DAY',-7,CURRENT_TIMESTAMP())
    )
);