USE DATABASE RETAIL_LAKEHOUSE;

CREATE OR REPLACE STREAM CUSTOMER_STREAM
ON TABLE RAW.RAW_CUSTOMERS;

CREATE OR REPLACE STREAM ORDER_STREAM
ON TABLE RAW.RAW_ORDERS;

CREATE OR REPLACE STREAM PRODUCT_STREAM
ON TABLE RAW.RAW_PRODUCTS;

CREATE OR REPLACE STREAM PAYMENT_STREAM
ON TABLE RAW.RAW_PAYMENTS;

CREATE OR REPLACE STREAM ORDER_ITEM_STREAM
ON TABLE RAW.RAW_ORDER_ITEMS;

SHOW STREAMS;