MERGE INTO TRANSFORM.CUSTOMERS_CLEAN tgt
USING (

    SELECT *
    FROM CUSTOMER_STREAM

) src

ON tgt.CUSTOMER_ID = src.CUSTOMER_ID

WHEN MATCHED THEN
UPDATE SET
    CUSTOMER_CITY = UPPER(TRIM(src.CUSTOMER_CITY)),
    CUSTOMER_STATE = UPPER(TRIM(src.CUSTOMER_STATE))

WHEN NOT MATCHED THEN
INSERT (
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_CITY,
    CUSTOMER_STATE
)
VALUES (
    src.CUSTOMER_ID,
    src.CUSTOMER_UNIQUE_ID,
    UPPER(TRIM(src.CUSTOMER_CITY)),
    UPPER(TRIM(src.CUSTOMER_STATE))
);

MERGE INTO TRANSFORM.ORDERS_CLEAN tgt
USING (
    SELECT *
    FROM ORDER_STREAM
) src

ON tgt.ORDER_ID = src.ORDER_ID

WHEN MATCHED THEN
UPDATE SET
    CUSTOMER_ID = src.CUSTOMER_ID,
    ORDER_STATUS = src.ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP = src.ORDER_PURCHASE_TIMESTAMP,
    ORDER_APPROVED_AT = src.ORDER_APPROVED_AT,
    ORDER_DELIVERED_CUSTOMER_DATE = src.ORDER_DELIVERED_CUSTOMER_DATE

WHEN NOT MATCHED THEN
INSERT (
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP,
    ORDER_APPROVED_AT,
    ORDER_DELIVERED_CUSTOMER_DATE
)
VALUES (
    src.ORDER_ID,
    src.CUSTOMER_ID,
    src.ORDER_STATUS,
    src.ORDER_PURCHASE_TIMESTAMP,
    src.ORDER_APPROVED_AT,
    src.ORDER_DELIVERED_CUSTOMER_DATE
);

MERGE INTO TRANSFORM.PRODUCTS_CLEAN tgt
USING (
    SELECT *
    FROM PRODUCT_STREAM
) src

ON tgt.PRODUCT_ID = src.PRODUCT_ID

WHEN MATCHED THEN
UPDATE SET
    PRODUCT_CATEGORY_NAME =
        COALESCE(src.PRODUCT_CATEGORY_NAME,'UNKNOWN'),
    PRODUCT_WEIGHT_G = src.PRODUCT_WEIGHT_G

WHEN NOT MATCHED THEN
INSERT (
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_WEIGHT_G
)
VALUES (
    src.PRODUCT_ID,
    COALESCE(src.PRODUCT_CATEGORY_NAME,'UNKNOWN'),
    src.PRODUCT_WEIGHT_G
);

MERGE INTO TRANSFORM.PAYMENTS_CLEAN tgt
USING (
    SELECT *
    FROM PAYMENT_STREAM
) src

ON tgt.ORDER_ID = src.ORDER_ID
AND tgt.PAYMENT_TYPE = src.PAYMENT_TYPE
AND tgt.PAYMENT_SEQUENTIAL = src.PAYMENT_SEQUENTIAL

WHEN MATCHED THEN
UPDATE SET
    PAYMENT_INSTALLMENTS = src.PAYMENT_INSTALLMENTS,
    PAYMENT_VALUE = src.PAYMENT_VALUE

WHEN NOT MATCHED THEN
INSERT (
    ORDER_ID,
    PAYMENT_SEQUENTIAL,
    PAYMENT_TYPE,
    PAYMENT_INSTALLMENTS,
    PAYMENT_VALUE
)
VALUES (
    src.ORDER_ID,
    src.PAYMENT_SEQUENTIAL,
    src.PAYMENT_TYPE,
    src.PAYMENT_INSTALLMENTS,
    src.PAYMENT_VALUE
);

MERGE INTO TRANSFORM.ORDER_ITEMS_CLEAN tgt
USING (
    SELECT *
    FROM ORDER_ITEM_STREAM
) src

ON tgt.ORDER_ID = src.ORDER_ID
AND tgt.ORDER_ITEM_ID = src.ORDER_ITEM_ID

WHEN MATCHED THEN
UPDATE SET
    PRODUCT_ID = src.PRODUCT_ID,
    PRICE = src.PRICE,
    FREIGHT_VALUE = src.FREIGHT_VALUE

WHEN NOT MATCHED THEN
INSERT (
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    PRICE,
    FREIGHT_VALUE
)
VALUES (
    src.ORDER_ID,
    src.ORDER_ITEM_ID,
    src.PRODUCT_ID,
    src.PRICE,
    src.FREIGHT_VALUE
);