USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE DYNAMIC_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DYNAMIC TABLE TRANSFORM.DT_CUSTOMERS
TARGET_LAG = '5 MINUTES'
WAREHOUSE = DYNAMIC_WH
AS

SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    UPPER(TRIM(CUSTOMER_CITY)) AS CUSTOMER_CITY,
    UPPER(TRIM(CUSTOMER_STATE)) AS CUSTOMER_STATE
FROM RAW.RAW_CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

CREATE OR REPLACE DYNAMIC TABLE TRANSFORM.DT_PRODUCTS
TARGET_LAG = '5 MINUTES'
WAREHOUSE = DYNAMIC_WH
AS

SELECT
    PRODUCT_ID,
    COALESCE(
        PRODUCT_CATEGORY_NAME,
        'UNKNOWN'
    ) AS PRODUCT_CATEGORY_NAME,
    PRODUCT_WEIGHT_G
FROM RAW.RAW_PRODUCTS;

CREATE OR REPLACE DYNAMIC TABLE MART.DT_SALES_SUMMARY
TARGET_LAG = '5 MINUTES'
WAREHOUSE = DYNAMIC_WH
AS

SELECT

    DATE_TRUNC(
        'MONTH',
        ORDER_PURCHASE_TIMESTAMP
    ) AS SALES_MONTH,

    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,

    SUM(p.PAYMENT_VALUE) AS TOTAL_REVENUE

FROM TRANSFORM.ORDERS_CLEAN o

JOIN TRANSFORM.PAYMENTS_CLEAN p
ON o.ORDER_ID = p.ORDER_ID

GROUP BY 1;

SELECT * FROM TRANSFORM.PAYMENTS_CLEAN
LIMIT 10;