version: 2

sources:

  - name: raw

    database: RETAIL_LAKEHOUSE

    schema: RAW

    tables:

      - name: RAW_CUSTOMERS

      - name: RAW_ORDERS

      - name: RAW_PRODUCTS

      - name: RAW_ORDER_ITEMS

      - name: RAW_PAYMENTS
      