USE DATABASE RETAIL_LAKEHOUSE;
USE SCHEMA TRANSFORM;

CREATE OR REPLACE TABLE TRANSFORM.ORDERS_CLEAN AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP,
    ORDER_APPROVED_AT,
    ORDER_DELIVERED_CUSTOMER_DATE
FROM RAW.RAW_ORDERS
WHERE ORDER_ID IS NOT NULL;