USE DATABASE RETAIL_LAKEHOUSE;
USE SCHEMA TRANSFORM;


CREATE OR REPLACE TABLE TRANSFORM.PRODUCTS_CLEAN AS
SELECT
    PRODUCT_ID,
    COALESCE(
        PRODUCT_CATEGORY_NAME,
        'UNKNOWN'
    ) AS PRODUCT_CATEGORY_NAME,
    PRODUCT_WEIGHT_G
FROM RAW.RAW_PRODUCTS
WHERE PRODUCT_ID IS NOT NULL;