USE DATABASE RETAIL_LAKEHOUSE;
USE SCHEMA TRANSFORM;
CREATE OR REPLACE TABLE TRANSFORM.PAYMENTS_CLEAN AS
SELECT
    ORDER_ID,
    PAYMENT_TYPE,
    PAYMENT_INSTALLMENTS,
    PAYMENT_VALUE
FROM RAW.RAW_PAYMENTS
WHERE PAYMENT_VALUE > 0;