-- Null Checks
SELECT COUNT(*)
FROM TRANSFORM.CUSTOMERS_CLEAN
WHERE CUSTOMER_ID IS NULL;

-- Duplicate Checks
SELECT
    CUSTOMER_ID,
    COUNT(*)
FROM TRANSFORM.CUSTOMERS_CLEAN
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

-- Revenue Validation
SELECT
    SUM(PAYMENT_VALUE)
FROM TRANSFORM.PAYMENTS_CLEAN;