USE ROLE ACCOUNTADMIN;

-- Ingestion warehouse

CREATE OR REPLACE WAREHOUSE INGEST_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

-- Transformation warehouse

CREATE OR REPLACE WAREHOUSE TRANSFORM_WH
WITH
WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

-- Analytics warehouse

CREATE OR REPLACE WAREHOUSE ANALYTICS_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;