USE ROLE SECURITYADMIN;

-- Database access

GRANT USAGE ON DATABASE RETAIL_LAKEHOUSE
TO ROLE DEVELOPER_ROLE;

GRANT USAGE ON DATABASE RETAIL_LAKEHOUSE
TO ROLE ANALYST_ROLE;

GRANT USAGE ON DATABASE RETAIL_LAKEHOUSE
TO ROLE READONLY_ROLE;

------------------------------------------------

-- Schema access

GRANT USAGE ON SCHEMA RETAIL_LAKEHOUSE.RAW
TO ROLE DEVELOPER_ROLE;

GRANT USAGE ON SCHEMA RETAIL_LAKEHOUSE.TRANSFORM
TO ROLE DEVELOPER_ROLE;

GRANT USAGE ON SCHEMA RETAIL_LAKEHOUSE.MART
TO ROLE ANALYST_ROLE;

------------------------------------------------

-- Warehouse access

GRANT USAGE ON WAREHOUSE INGEST_WH
TO ROLE DEVELOPER_ROLE;

GRANT USAGE ON WAREHOUSE TRANSFORM_WH
TO ROLE DEVELOPER_ROLE;

GRANT USAGE ON WAREHOUSE ANALYTICS_WH
TO ROLE ANALYST_ROLE;