USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR RETAIL_MONITOR
WITH CREDIT_QUOTA = 50
FREQUENCY = MONTHLY
START_TIMESTAMP = IMMEDIATELY
TRIGGERS
ON 75 PERCENT DO NOTIFY
ON 90 PERCENT DO NOTIFY
ON 100 PERCENT DO SUSPEND;